In [2]:
import matplotlib.pyplot as plt
import numpy.random
import numpy as np
import seaborn
%pylab inline
pylab.rcParams['figure.figsize'] = (8, 8)
#seaborn.set_context("talk")

Populating the interactive namespace from numpy and matplotlib


In [54]:
import sklearn.naive_bayes #MultinomialNB
from collections import Counter

In [7]:
!head -n 3 rt-polarity.neg

simplistic , silly and tedious . 
it's so laddish and juvenile , only teenage boys could possibly find it funny . 
exploitative and largely devoid of the depth or sophistication that would make watching such a graphic treatment of the crimes bearable . 


In [8]:
!head -n 3 rt-polarity.pos

the rock is destined to be the 21st century's new " conan " and that he's going to make a splash even greater than arnold schwarzenegger , jean-claud van damme or steven segal . 
the gorgeously elaborate continuation of " the lord of the rings " trilogy is so huge that a column of words cannot adequately describe co-writer/director peter jackson's expanded vision of j . r . r . tolkien's middle-earth . 
effective but too-tepid biopic


In [64]:
data_neg = [l.strip().split() for l in open("rt-polarity.neg", encoding = "ISO-8859-1")]
data_pos = [l.strip().split() for l in open("rt-polarity.pos", encoding = "ISO-8859-1")]
dictionary = {}
rev_dictionary = {}
counts = Counter()
for sent in data_pos + data_neg:
    for word in sent:
        counts[word] += 1
        if word not in dictionary:
            key = len(dictionary)
            dictionary[word] = key
            rev_dictionary[key] = word


In [65]:
npos = len(data_pos)
nneg = len(data_neg)
n = npos + nneg
m = len(dictionary)
X = np.zeros((n, m))
y = np.zeros((n,))
y[:npos] = 1

In [66]:
for i,sent in enumerate(data_pos + data_neg):
    for word in sent:
        j = dictionary[word]
        X[i, j] += 1

In [103]:
def encode(sent):
    x = np.zeros((1, m))
    for word in sent.split():
        if word in dictionary:
            x[0, dictionary[word]] += 1
    return x

In [93]:
model = sklearn.naive_bayes.MultinomialNB()

In [94]:
X.shape, y.shape

((10662, 21401), (10662,))

In [95]:
model.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [110]:
features = []
for word, _ in counts.most_common(1000):
    j = dictionary[word]
    pi = model.feature_log_prob_[:, j]
    print("%10s \t %d \t %s"%(word, j, pi))
    features.append((word, pi[1]/pi[0]))

         . 	 30 	 [-2.93901082 -2.95454721]
       the 	 0 	 [-3.27148481 -3.27680855]
         , 	 23 	 [-3.32813063 -3.23475216]
         a 	 16 	 [-3.65123352 -3.55346689]
       and 	 11 	 [-3.9166723  -3.62964515]
        of 	 34 	 [-3.87851246 -3.69873863]
        to 	 4 	 [-4.07290218 -4.21855921]
        is 	 2 	 [-4.38305711 -4.36068435]
        in 	 122 	 [-4.63505983 -4.60392314]
      that 	 12 	 [-4.70068337 -4.66310291]
        it 	 81 	 [-4.72242335 -4.8003739 ]
        as 	 71 	 [-4.97060298 -5.02442613]
       but 	 55 	 [-5.04596184 -5.14121534]
      with 	 118 	 [-5.27908493 -5.01876039]
      film 	 85 	 [-5.36208185 -5.09139183]
      this 	 146 	 [-5.14536919 -5.30155799]
       for 	 252 	 [-5.15966443 -5.29111792]
       its 	 158 	 [-5.33989394 -5.2532677 ]
        an 	 74 	 [-5.4561108  -5.17498478]
     movie 	 76 	 [-5.16491379 -5.56797844]
      it's 	 129 	 [-5.47387326 -5.4675223 ]
        be 	 5 	 [-5.54248218 -5.76409332]
        on 	 416 	 [-5.6412532

In [114]:
features.sort(key=lambda x: x[1])
for w, s in features[:10]:
    print(w, s)

engrossing 0.748111378087
warm 0.776461269278
wonderful 0.776461269278
inventive 0.776787766429
powerful 0.778614896302
refreshing 0.784623039792
captures 0.78853756099
provides 0.78853756099
touching 0.791720607205
portrait 0.799052481715


In [115]:
for w, s in features[-10:]:
    print(w, s)

stupid 1.2698157418
routine 1.29510890358
mediocre 1.30105671246
generic 1.30105671246
bad 1.3103589716
dull 1.31548145632
flat 1.316062605
boring 1.33720814855
badly 1.36938558593
unfunny 1.38835558023


In [107]:
model.predict(encode("the film was excellent"))

array([ 1.])

In [116]:
model.predict(encode("professor parkes lecture was an engrossing portait of Bayesian ideals"))

array([ 1.])

In [122]:
model.predict_proba(encode("professor parkes lecture was an engrossing portait of Bayesian ideals"))

array([[ 0.25657334,  0.74342666]])

In [127]:
model.predict_proba(encode("professor rush boldly satirized the boring flat dull routine of modern existence"))

array([[  9.99937145e-01,   6.28550516e-05]])